config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :comparisons
  resources :projects do
    resources :scenarios do
      member do
        post 'run'
      end
    end
  end
  resources :project_tokens, only: [:create]
  resources :revisions

  namespace :api do
    resources :revisions
    resources :images
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
end

app/models/comparison.rb
class Comparison < ApplicationRecord
  belongs_to :from_revision, class_name: 'Revision'
  belongs_to :to_revision, class_name: 'Revision'

  has_many :comparison_image_diffs
  has_many :image_diffs, through: :comparison_image_diffs
  has_one :scenario, through: :from_revision

  delegate :project, to: :scenario
end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  def create
    require 'whattheshift/revision_compare'
    Comparison.transaction do
      @comparison = WhatTheShift::RevisionCompare.new.call(*revisions)
      authorize @comparison
    end
    render :show
  end

  def index
    @comparisons = policy_scope(Comparison).includes(:image_diffs).all
  end

  def show
    @comparison = Comparison.includes(:image_diffs).find(params[:id])
    authorize @comparison
  end

  private

  def comparision_params
    params.require(:comparison)
          .permit(revision_ids: [])
  end

  def revisions
    revision_ids = comparision_params[:revision_ids]
    raise 'Must select 2 Revisions' unless revision_ids.length == 2
    Revision.where(id: comparision_params[:revision_ids])
  end
end

app/views/comparisons/index.html.erb
<h1>Listing comparisons</h1>

<table>
  <tr>
    <th>ID</th>
    <th>From</th>
    <th>To</th>
    <th>Images</th>
    <th></th>
  </tr>

  <% @comparisons.each do |comparison| %>
    <tr>
      <td><%= comparison.id %></td>
      <td><%= link_to "Revision #{comparison.from_revision_id}", revision_path(comparison.from_revision_id) %></td>
      <td><%= link_to "Revision #{comparison.to_revision_id}", revision_path(comparison.to_revision_id) %></td>
      <td><%= comparison.image_diffs.count %></td>
      <td><%= link_to 'Show', comparison_path(comparison) %></td>
    </tr>
  <% end %>
</table>

app/views/comparisons/show.html.erb
<p>
  <strong>ID:</strong>
  <%= @comparison.id %>
</p>

<p>
  <strong>From:</strong>
  <%= link_to "Revision #{@comparison.from_revision_id}", revision_path(@comparison.from_revision_id) %>
</p>

<p>
  <strong>To:</strong>
  <%= link_to "Revision #{@comparison.to_revision_id}", revision_path(@comparison.to_revision_id) %>
</p>

<h2>Image Diff</h2>
<table>
  <tr>
    <th>ID</th>
    <th>Before</th>
    <th>After</th>
    <th>Diff</th>
  </tr>

  <% @comparison.image_diffs.each do |image_diff| %>
    <tr>
      <td><%= image_diff.id %></td>
      <td><%= image_tag(image_diff.before_image.image) %></td>
      <td><%= image_tag(image_diff.after_image.image) %></td>
      <td><%= image_tag(image_diff.image) %></td>
    </tr>
  <% end %>
</table>