config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :comparisons
  resources :projects do
    resources :scenarios do
      member do
        post 'run'
      end
    end
  end
  resources :project_tokens, only: [:create]
  resources :revisions

  namespace :api do
    resources :revisions
    resources :images
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
end

app/models/image.rb
class Image < ApplicationRecord
  has_and_belongs_to_many :revisions

  has_one_attached :image
end

app/models/revision.rb
class Revision < ApplicationRecord
  belongs_to :scenario
  has_and_belongs_to_many :images

  accepts_nested_attributes_for :images

  before_save :find_or_create_images

  private

  # Avoid creating new images when existing images can be shared between revisions
  def find_or_create_images
    self.images = images.map do |image|
      Image.find_by(image.attributes.compact) || image
    end
  end
end

app/controllers/api/revisions_controller.rb
module Api
  class RevisionsController < ApiController
    before_action :set_revision, only: [:show]
    before_action :load_scenario, only: [:create]

    def show
      render(@revision)
    end

    def create
      @revision = @scenario.revisions.create!(revision_params)
      render(@revision, status: :created)
    end

    private

    def load_scenario
      api_key = params.require(:api_key)
      project = ProjectToken.find(api_key).project
      @scenario = project.scenarios.first
    end

    def revision_params
      params.require(:revision)
            .permit :description,
                    :identifier,
                    images_attributes: [:identifier, :signature]
    end

    def set_revision
      @revision = Revision.find(params[:id])
    end
  end
end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def index
    @revisions = Revision.includes(:images).all
  end

  def show
    @revision = Revision.includes(:images).find(params[:id])
  end
end

app/views/revisions/_from_scenario_form.html.erb
<%= form_tag(run_project_scenario_path(@project, @scenario)) do %>
  <p>
    <%= label_tag(:description) %>
    <%= text_field_tag(:description, nil, placeholder: 'New brand colours') %>
    <%= submit_tag('Run') %>
  </p>
<% end %>

app/views/revisions/index.html.erb
<h1>Listing revisions</h1>

<%= form_for(:comparison, url: comparisons_path) do |f| %>
  <table>
    <tr>
      <th></th>
      <th>ID</th>
      <th>Description</th>
      <th>Identifier</th>
      <th>Images</th>
      <th></th>
    </tr>

    <% @revisions.each do |revision| %>
      <tr>
        <td><%= f.check_box :revision_ids, { multiple: true }, revision.id, nil %></td>
        <td><%= revision.id %></td>
        <td><%= revision.description %></td>
        <td><%= revision.identifier %></td>
        <td><%= revision.images.count %></td>
        <td><%= link_to 'Show', revision_path(revision) %></td>
      </tr>
    <% end %>
  </table>

  <%= f.button'Compare Selected' %>
<% end %>

app/views/revisions/show.html.erb
<p>
  <strong>ID:</strong>
  <%= @revision.id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @revision.description %>
</p>

<p>
  <strong>Identifier:</strong>
  <%= @revision.identifier %>
</p>

<p>
  <%= link_to 'Project', @revision.scenario.project %>
</p>

<h2>Images</h2>
<table>
  <tr>
    <th>ID</th>
    <th>Identifier</th>
    <th>Signature</th>
    <th>Image</th>
  </tr>

  <% @revision.images.each do |image| %>
    <tr>
      <td><%= image.id %></td>
      <td><%= image.identifier %></td>
      <td><%= image.signature %></td>
      <td><%= image_tag(image.image) if image.image.attached? %></td>
    </tr>
  <% end %>
</table>