config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :comparisons
  resources :projects do
    resources :scenarios do
      member do
        post 'run'
      end
    end
  end
  resources :project_tokens, only: [:create]
  resources :revisions

  namespace :api do
    resources :revisions
    resources :images
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
end

app/models/scenario.rb
class Scenario < ApplicationRecord
  belongs_to :project
  has_many :revisions
  has_one :script, dependent: :destroy

  accepts_nested_attributes_for :script
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :load_project
  before_action :load_scenario, only: [:destroy, :edit, :run, :show, :update]

  def create
    @scenario = @project.scenarios.create(scenario_params)
    authorize @scenario
    render :show
  end

  def destroy
    @scenario.destroy
    flash[:notice] = "Scenario deleted!"
    redirect_to project_scenarios_path(@project)
  end

  def index
    @scenarios = policy_scope(Scenario)
  end

  def new
    @scenario = @project.scenarios.new
    @scenario.script = NavigationScript.new
    authorize @scenario
  end

  def update
    @scenario.update(scenario_params)
    render :show
  end

  def run
    authorize @scenario
    require 'whattheshift/scripting/revision_from_scenario'
    runner = WhatTheShift::Scripting::RevisionFromScenario.new(capybara_driver, @scenario)
    revision = runner.call(run_params[:description])
    flash[:notice] = "Revision created!"
    redirect_to revision_path(revision)
  end

  private

  def capybara_driver
    require 'whattheshift/scripting/capybara_driver'
    WhatTheShift::Scripting::CapybaraDriver.new
  end

  def load_project
    @project = Project.find(params[:project_id])
  end

  def load_scenario
    @scenario = Scenario.includes(:script).find(params[:id])
    authorize @scenario
  end

  def scenario_params
    params.require(:scenario)
          .permit :name,
                  script_attributes: [
                    :type,
                    {
                      destinations_attributes: [
                        :description,
                        :is_full_height,
                        :url
                      ]
                    }
                  ]
  end

  def run_params
    params.permit(:description)
  end
end

app/views/scenarios/_form.html.erb
<%= form_for([@project, @scenario]) do |f| %>
  <p>
    <%= f.label(:name) %>
    <%= f.text_field(:name) %>
  </p>

  <h2>Script</h2>
  <% # Only NavigationScript type currently supported %>
  <%= f.fields_for :script do |ff| %>
    <p>
      <%= ff.label :type %>
      <%= ff.select :type, Script.types %>
    </p>
    <% script = ff.object %>
    <%= render partial: "navigation_script_form", locals: { f: ff, script: script } %>
  <% end %>

  <p>
    <%= f.submit('Save') %>
  </p>
<% end %>

app/views/scenarios/_navigation_script.html.erb
<ul>
  <% script.destinations.each do |destination| %>
    <li>
      <%= destination.description %>
      <%= destination.url %>
      <%= '(full-height)' if destination.full_height? %>
    </li>
  <% end %>
</ul>

app/views/scenarios/_navigation_script_form.html.erb
<table>
  <tr>
    <th>Description</th>
    <th>URL</th>
  </tr>

  <%= f.fields_for :destinations, script.fill_destinations do |ff| %>
    <tr>
      <td><%= ff.text_field :description, placeholder: 'About Page' %></td>
      <td><%= ff.text_field :url, placeholder: 'https://my-site.com/about' %></td>
      <td><%= ff.check_box :is_full_height, {}, 'true', 'false' %></td>
    </tr>
  <% end %>
</table>

(currently limited to 5 urls per script)

app/views/scenarios/edit.html.erb
<h1>Edit Scenario <%= @scenario.id %></h1>

<%= render 'form' %>

app/views/scenarios/index.html.erb
<h1>Project <%= @project.id %> Scenarios</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

  <% @project.scenarios.each do |scenario| %>
    <tr>
      <td><%= scenario.name %></td>
      <td>
        <%= link_to 'Show', project_scenario_path(@project, scenario) %>
        <%= link_to 'Edit', edit_project_scenario_path(@project, scenario) %>
        <%= link_to 'Delete', project_scenario_path(@project, scenario), method: :delete %>
      </td>
    </tr>
  <% end %>

  <tr>
    <td></td>
    <td><%= link_to 'Add new scenario', new_project_scenario_path(@project) %></td>
  </tr>
</table>

app/views/scenarios/new.html.erb
<h1>Create Scenario</h1>

<%= render 'form' %>

app/views/scenarios/show.html.erb
<h1>Project <%= @project.id %> Scenario <%= @scenario.id %></h1>

<p>
  <%= link_to 'Projects', projects_path %> /
  <%= link_to @project.id, @project %> /
  <%= link_to 'Scenarios', [@project, :scenarios] %> /
  <%= link_to 'edit', edit_project_scenario_path(@project, @scenario) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @scenario.name %>
</p>

<% if @scenario.script %>
  <h2>Script</h2>

  <%= render partial: @scenario.script.partial_name, locals: { script: @scenario.script } %>
<% end %>

<h2>Run Now</h2>

<%= render partial: '/revisions/from_scenario_form', locals: { scenario: @scenario } %>